# Default pigeon config.
# Priority: --config > PIGEON_CONFIG > this file.

cache = "/tmp/pigeon-cache"
namespace = "demo"
user = "pgroup"

[worker]
max_jobs = 4
poll_interval = 5
debug = true

[remote_env]
# Example:
HTTPS_PROXY="http://proxy.example:8080"
